config_version = "0"

exclude_patterns = [
  "**/.build/**",
  "**/DerivedData/**",
  "**/*.xcresult/**",
  "**/vendor/**"
]

test_patterns = [
  "**/*Tests/**",
  "**/*UITests/**",
  "**/*Tests.swift"
]

[[source]]
name = "default"
default = true

[[plugin]]
name = "swiftlint"

[[plugin]]
name = "swiftformat"
