/**
 * Write Spec stage.
 * Placeholder agent call for spec generation.
 * Real implementation would call spec agent with Claude API.
 */

import { writeFileSync } from 'fs';

const specPath = 'specs/factory/goal-to-production-spec.md';

const placeholderSpec = `# Generated Spec

## Purpose
Placeholder spec generated by workflow.

## Acceptance Criteria
- Placeholder criterion 1
- Placeholder criterion 2

## Definition of Done
- [ ] Placeholder task 1
- [ ] Placeholder task 2
`;

writeFileSync(specPath, placeholderSpec, 'utf8');

console.log(JSON.stringify({
  spec_path: specPath,
  adr_required: false,
  work_packages: ['wp-001'],
  reviewers: ['spec-review'],
  quality_gates: ['spec-approval']
}));
