vcs:
  type: git
agents:
  available:
  - codex
  - claude
  auto_commit: true
project:
  uuid: c1021e57-4f6e-4454-a311-c34144278575
  slug: maestro-os
  node_id: a88bbae85719
  build_id: cd430d27-a6cb-4fa8-a1c5-4c2fc2c33076
